name: quizzle_quiz_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  websafe_svg: ^3.0.1+6
  flutter_svg: ^2.0.15
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter_native_splash:
  color: "#353a65"   # Color of the background of the splash screen 
  image: assets/images/splash_screen.png  # image path
  android_12:
    image: assets/images/splash_screen.png  # image path
    color: "#353a65"   # Color of the background of the splash screen 



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"  # Logo image path 
  min_sdk_android: 21



flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
